### ISSUE TITLE
Working Session: Front-End

### ISSUE THREAD

**Issue by ani6gup** [Project6c613/platform#7]

**Comment by ani6gup** [comment]
# 01/16 Working Session

## Group

- [ ] Are there any other pages that need to be made? How has the work been split up? 
- Reference CTF Guide
- Instruction Page 
- [ ] Go through [Front-End Modifications](https://github.com/Project6c613/platform/issues/5)
- [ ] Plan Next Steps 
- [ ] Schedule Next Working Session 

## Individual 

**(Tentative: Based on next Steps)**

- [ ] Start working on modifications 
- [ ] Build Pages

**Comment by ani6gup** [comment]
# 01/16 Working Session

## Group
- [ ] Figure out a way to signify a question/room has been completed 
- [ ] Brainstorm Storyline for Introduction
- [X] Are there any other pages that need to be made? How has the work been split up? 
- Reference CTF Guide
- Instruction Page 
- [X] Go through Front-End Modifications 
- [X] Plan Next Steps 
- [X] Schedule Next Working Session

## Individual 

### Meera 
- [ ] Complete Front End Modifications 

### Sarah 
- [ ] Mock-Up Storyline and how it will be presented in platform 

## Additional

- Check-in Next Tuesday 
- Follow-Up on Instruction Page

**Comment by meerabenson** [comment]
Need a view when a user logs in and there is no live game

**Comment by sfallahadl** [comment]
Understand how to access the database so we can compare user's answer to the saved answers. Send a flag from the database to show that rooms were unlocked.
